name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn build
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            RELEASE_NAME=$(date +%y%m%d%H)
          else
            RELEASE_NAME=${GITHUB_REF#refs/tags/}
          fi
          gh release create "$RELEASE_NAME" public/*