name: Release

on:
  push:
    tags:
      - '*'
    paths:
      - 'data/**'
  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn build
          if [[ "${GITHUB_REF}" =~ ^refs/tags/ ]]; then
              RELEASE_NAME=${GITHUB_REF#refs/tags/}
          else
              RELEASE_NAME=$(date +%y%m%d%H)
          fi
          gh release create "$RELEASE_NAME" public/*